// Mocks generated by Mockito 5.4.4 from annotations
// in starkeep/test/notes/data/datasources/notes_local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:starkeep/core/notes/data/datasources/notes_local_data_source.dart'
    as _i3;
import 'package:starkeep/core/notes/domain/entities/note.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNote_0 extends _i1.SmartFake implements _i2.Note {
  _FakeNote_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotesLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesLocalDataSourceImpl extends _i1.Mock
    implements _i3.NotesLocalDataSourceImpl {
  @override
  _i4.Future<List<_i2.Note>> loadNotes() => (super.noSuchMethod(
        Invocation.method(
          #loadNotes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i4.Future<List<_i2.Note>>);

  @override
  _i4.Future<_i2.Note> createNote({
    String? title = r'',
    String? content = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [],
          {
            #title: title,
            #content: content,
          },
        ),
        returnValue: _i4.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #createNote,
            [],
            {
              #title: title,
              #content: content,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #createNote,
            [],
            {
              #title: title,
              #content: content,
            },
          ),
        )),
      ) as _i4.Future<_i2.Note>);

  @override
  _i4.Future<_i2.Note> updateNote({
    required String? id,
    required String? title,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [],
          {
            #id: id,
            #title: title,
            #content: content,
          },
        ),
        returnValue: _i4.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #updateNote,
            [],
            {
              #id: id,
              #title: title,
              #content: content,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #updateNote,
            [],
            {
              #id: id,
              #title: title,
              #content: content,
            },
          ),
        )),
      ) as _i4.Future<_i2.Note>);
}
